_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.11
            "6": 4.52.2
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
bos_token_id:
    value: 101
dropout:
    value: 0.1
eos_token_id:
    value: 102
hidden_size:
    value: 768
intermediate_size:
    value: 3072
layer_norm_eps:
    value: 1e-12
learning_rate:
    value: 5e-05
max_code_length:
    value: 512
max_error_length:
    value: 128
max_grad_norm:
    value: 1
max_length:
    value: 512
max_position_embeddings:
    value: 512
max_span_length:
    value: 5
mlm_probability:
    value: 0.15
num_attention_heads:
    value: 12
num_beams:
    value: 4
num_epochs:
    value: 3
num_hidden_layers:
    value: 6
pad_token_id:
    value: 0
repetition_penalty:
    value: 1
span_masking:
    value: true
temperature:
    value: 1
top_k:
    value: 50
top_p:
    value: 0.95
unk_token_id:
    value: 3
use_ast:
    value: true
use_data_flow:
    value: true
vocab_size:
    value: 30522
warmup_steps:
    value: 1000
weight_decay:
    value: 0.01
